name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tagcreated: ${{ steps.autotag.outputs.tagcreated }}
      tagname: ${{ steps.autotag.outputs.tagname }}
    steps:
    - uses: actions/checkout@v2
    - uses: bullrich/commit-autotag@main
      id: autotag
      with:
        tag_prefix: "v"
        head_branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-version:
    runs-on: ubuntu-latest
    needs: [tag]
    # important, only triggers if tag was created
    if: needs.tag.outputs.tagcreated == 'true'
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g generate-changelog
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get previous version
        id: previous-tag
        run: |
          PREVIOUS_TAG=$(git tag | sort -V | tail -n 2 | head -n 1 )
          echo "::set-output name=previous_tag::$PREVIOUS_TAG"
      - name: Generate changelog
        id: changelog
        run: |
          changelog=$(generate-changelog -t "${{ steps.previous-tag.outputs.previous_tag }}..${{ needs.tag.outputs.tagname }}" --file -)
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.tagname }}
          release_name: Release ${{ needs.tag.outputs.tagname }}
          body: |
            ## Changes
            ${{ env.changelog }}
